[2022-11-04T17:29:52.856+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2022-11-04T17:29:52.875+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2022-11-04T17:29:52.875+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:29:52.877+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T17:29:52.878+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:29:52.900+0000] {taskinstance.py:1383} INFO - Executing <Task(HelloOperator): hello_Custom-Operator> on 2022-11-03 00:00:00+00:00
[2022-11-04T17:29:52.909+0000] {standard_task_runner.py:55} INFO - Started process 2096 to run task
[2022-11-04T17:29:52.915+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customoperator', 'hello_Custom-Operator', 'scheduled__2022-11-03T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/4-customoperator.py', '--cfg-path', '/tmp/tmp4wmspssh']
[2022-11-04T17:29:52.916+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask hello_Custom-Operator
[2022-11-04T17:29:52.989+0000] {task_command.py:376} INFO - Running <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-03T00:00:00+00:00 [running]> on host c7d12af55512
[2022-11-04T17:29:53.066+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customoperator
AIRFLOW_CTX_TASK_ID=hello_Custom-Operator
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T00:00:00+00:00
[2022-11-04T17:29:53.068+0000] {taskinstance.py:1851} ERROR - Task failed with exception
TypeError: execute() got an unexpected keyword argument 'context'
[2022-11-04T17:29:53.086+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=customoperator, task_id=hello_Custom-Operator, execution_date=20221103T000000, start_date=20221104T172952, end_date=20221104T172953
[2022-11-04T17:29:53.102+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 23 for task hello_Custom-Operator (execute() got an unexpected keyword argument 'context'; 2096)
[2022-11-04T17:29:53.132+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-04T17:29:53.152+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-04T17:36:15.127+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2022-11-04T17:36:15.145+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2022-11-04T17:36:15.146+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:36:15.147+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T17:36:15.147+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T17:36:15.169+0000] {taskinstance.py:1383} INFO - Executing <Task(HelloOperator): hello_Custom-Operator> on 2022-11-03 00:00:00+00:00
[2022-11-04T17:36:15.178+0000] {standard_task_runner.py:55} INFO - Started process 2403 to run task
[2022-11-04T17:36:15.181+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'customoperator', 'hello_Custom-Operator', 'scheduled__2022-11-03T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/4-customoperator.py', '--cfg-path', '/tmp/tmpjeaez_p6']
[2022-11-04T17:36:15.182+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask hello_Custom-Operator
[2022-11-04T17:36:15.261+0000] {task_command.py:376} INFO - Running <TaskInstance: customoperator.hello_Custom-Operator scheduled__2022-11-03T00:00:00+00:00 [running]> on host c7d12af55512
[2022-11-04T17:36:15.374+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=customoperator
AIRFLOW_CTX_TASK_ID=hello_Custom-Operator
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T00:00:00+00:00
[2022-11-04T17:36:15.375+0000] {logging_mixin.py:120} INFO - Hi Freddy M
[2022-11-04T17:36:15.385+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=customoperator, task_id=hello_Custom-Operator, execution_date=20221103T000000, start_date=20221104T173615, end_date=20221104T173615
[2022-11-04T17:36:15.436+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-04T17:36:15.455+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
